### ISSUE TITLE
此插件未声明配置项，这可能并非预期行为。请联系插件作者并反馈此问题。

### ISSUE THREAD

**Issue by s567901** [LolitaOT/koishi-plugin-wws-kokomi#1]
启用插件后，koishi提示：

## 此插件未声明配置项，这可能并非预期行为。请联系插件作者并反馈此问题。

###日志：
```
2024-07-31 00:31:45 [W] config failed to resolve koishi-plugin-wws-kokomi
2024-07-31 00:31:45 [W] config Error: Cannot find module 'C:\Users\Kitakaze\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-wws-kokomi\lib\index.js'. Please verify that the package.json has a valid "main" entry
                            at tryPackage (node:internal/modules/cjs/loader:443:19)
                            at Module._findPath (node:internal/modules/cjs/loader:714:18)
                            at Module._resolveFilename (node:internal/modules/cjs/loader:1129:27)
                            at Function.resolve (node:internal/modules/helpers:190:19)
                            at PackageScanner.parsePackage (C:\Users\Kitakaze\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\plugin-config\lib\node\index.js:63:29)
                            at async PackageScanner.loadPackage (C:\Users\Kitakaze\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\registry\lib\index.js:166:14)
                            at async Promise.all (index 37)
                            at async PackageScanner.collect (C:\Users\Kitakaze\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\registry\lib\index.js:144:20)
                            at async Proxy.collect (C:\Users\Kitakaze\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\plugin-config\lib\node\index.js:80:5)
                            at async Proxy.get (C:\Users\Kitakaze\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\plugin-config\lib\shared\index.js:70:22)
2024-07-31 00:31:45 [I] adapter connect to server: wss://sandbox.api.sgroup.qq.com/websocket
2024-07-31 00:31:52 [E] app cannot resolve plugin "wws-kokomi"
2024-07-31 00:31:56 [I] loader apply plugin wws-kokomi:am9hfz
2024-07-31 00:31:56 [E] app cannot resolve plugin "wws-kokomi"
2024-07-31 00:32:22 [I] loader apply plugin wws-kokomi:am9hfz
2024-07-31 00:32:22 [E] app cannot resolve plugin "wws-kokomi"
```

**Comment by LolitaOT** [comment]
重新安装下最新版的试下，之前发布的版本忘记上传源文件了。
